### ISSUE TITLE
plugin.yml is not included in build jar after packaging

### ISSUE THREAD

**Issue by RepComm** [hb432/grakkit#1]
Spigot fails to load the plugin when:
1. cloning repo
2. running `mvn package`
3. copying output jar to plugins directory
4. running the server

```java
[16:08:40] [Server thread/ERROR]: Could not load 'plugins/grakkit-plugin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-a03b1fd-95bd423]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-a03b1fd-95bd423]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2-R0.1-SNAPSHOT.jar:git-Spigot-a03b1fd-95bd423]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more
```

**Comment by RepComm** [comment]
Going to try and patch this and pull request

**Comment by RepComm** [comment]
Latest release does not include `plugin.yml` and causes error:
`Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more
`

**Comment by RepComm** [comment]
Travis seems to be building release jar incorrectly

**Comment by grakkit** [comment]
Travis deployment has been disabled in favor of manual deployment. This will prevent any faulty automated releases.
