### ISSUE TITLE
Grakkit and Coreprotect not working well together

### ISSUE THREAD

**Issue by MercerK** [hb432/grakkit#14]
Hi folks!

I ran into a unique issue between Grakkit and Coreprotect, as my Coreprotect wasn't connecting to my MariaDB Server. When testing this with just Coreprotect, it works fine, but when using Grakkit and Coreprotect together, Coreprotect is unable connect to MariaDB (receiving `no suitable driver found for` error). 

I did some testing locally and I am able to recreate it. 

* Basically add CoreProtect and Grakkit together on a paper server (no configs or anything)
* Start server
* You'll see a ton of errors with Coreprotect. 
* Turn server off
* Disable Grakkit
* Turn server back on
* Coreprotect works fine

Any thoughts on what Grakkit may be doing to break it?

**Comment by ghost** [comment]
this is a very peculiar issue -- i will investigate this when i have the time. in the meantime, you could join the Grakkit discord server and talk with some of the developers there. they may be able to help you find a solution or a temporary monkey-patch fix until the issue can properly be resolved. hope that helps!

**Comment by MercerK** [comment]
In the process of launching a new 1.18 server using the latest Grakkit, Paper (v112), and CoreProtect (along with several other plugins). However, CoreProtect fails to start with Grakkit now. 

EDIT: This is just with default settings, as it won't even connect to the SQLite DB now.

```
[17:05:03 INFO]: [CoreProtect] Enabling CoreProtect v20.3
[17:05:03 WARN]: java.sql.SQLException: No suitable driver found for jdbc:sqlite:plugins\CoreProtect\database.db
[17:05:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[17:05:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.getConnection(Database.java:166)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.getConnection(Database.java:130)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.createDatabaseTables(Database.java:362)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:235)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:398)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:05:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[17:05:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:05:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:03 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "connection" is null
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.createDatabaseTables(Database.java:363)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.loadDatabase(ConfigHandler.java:235)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:398)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:05:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[17:05:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:05:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:03 WARN]: java.sql.SQLException: No suitable driver found for jdbc:sqlite:plugins\CoreProtect\database.db
[17:05:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[17:05:03 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.getConnection(Database.java:166)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.database.Database.getConnection(Database.java:130)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:405)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:05:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[17:05:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:05:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:03 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "connection" is null
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.config.ConfigHandler.performInitialization(ConfigHandler.java:406)
[17:05:03 WARN]:        at CoreProtect-20.3.jar//net.coreprotect.CoreProtect.onEnable(CoreProtect.java:71)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:05:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:05:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[17:05:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[17:05:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[17:05:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:05:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:05:03 INFO]: [CoreProtect] CoreProtect was unable to start.
[17:05:03 INFO]: [CoreProtect] Disabling CoreProtect v20.3
[17:05:03 INFO]: [CoreProtect] Finishing up data logging. Please wait...
[17:05:03 INFO]: [CoreProtect] Success! Disabled CoreProtect v20.3
```

**Comment by MercerK** [comment]
This impacts Lands as well.

```
[17:52:47 INFO]: [Lands]
[17:52:47 INFO]: [Lands] Using SQLite.
[17:52:47 INFO]: [Lands] Could not write to disk, please make sure that Lands has access to write and read to/from your disk: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 INFO]: [Lands] Could not write to disk, please make sure that Lands has access to write and read to/from your disk: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 INFO]: [Lands] Could not write to disk, please make sure that Lands has access to write and read to/from your disk: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 INFO]: [Lands] Could not write to disk, please make sure that Lands has access to write and read to/from your disk: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 INFO]: [Lands] Could not write to disk, please make sure that Lands has access to write and read to/from your disk: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 WARN]: java.lang.Throwable: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.Lands.onEnable(?:195)
[17:52:47 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:52:47 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:52:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:52:47 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[17:52:47 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[17:52:47 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[17:52:47 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[17:52:47 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[17:52:47 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[17:52:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:52:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:52:47 WARN]: Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.util.DriverDataSource.<init>(?:114)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.pool.PoolBase.initializeDataSource(?:331)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.pool.PoolBase.<init>(?:114)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.pool.HikariPool.<init>(?:108)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.HikariDataSource.<init>(?:81)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.gbbUs.gbbUs.gbbUs.KqghQ(?:608)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.gbbUs.NeDiR.eitR(?:905)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.Lands.onEnable(?:182)
[17:52:47 WARN]:        ... 11 more
[17:52:47 WARN]: Caused by: java.sql.SQLException: No suitable driver
[17:52:47 WARN]:        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299)
[17:52:47 WARN]:        at Lands-5.24.1.jar//me.angeschossen.lands.hikari.util.DriverDataSource.<init>(?:106)
[17:52:47 WARN]:        ... 18 more
[17:52:47 WARN]: [Lands] Error while initializing database. Disabling Lands. Error: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:\D:\Workspace\game-servers\s2-survival-mc\plugins\Lands\Data\database.db
[17:52:47 INFO]: [Lands] Disabling Lands v5.24.1
[17:52:47 INFO]: [Lands] Closing storage.
```
