### ISSUE TITLE
error with grakkit

### ISSUE THREAD

**Issue by Mantou1233** [hb432/grakkit#40]
error log:
```
[07:47:41] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:48:56] [Server thread/INFO]: oh no Onion4life gone!! now 2 ppl online
[07:48:57] [Server thread/INFO]: shinicore lost connection: Disconnected
[07:49:06] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:51:12] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:52:55] [Paper Watchdog Thread/ERROR]: ------------------------------
[07:53:13] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:53:17] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[07:53:22] [Server thread/WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 1869.313536ms. Summary: Getting prefix for shinicore
[07:53:23] [Server thread/WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 171.040892ms. Summary: Getting suffix for shinicore
[07:53:41] [User Authenticator #14/INFO]: UUID of player shinicore is 0cb1e209-1e40-35a7-97a9-fe31b83a16a6
[07:55:16] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:57:23] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[07:57:26] [Server thread/INFO]: oh no mantou gone!! now 1 ppl online
[07:59:26] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[08:01:32] [DiscordSRV - JDA Gateway/WARN]: [DiscordSRV] [JDA] Missed 2 heartbeats! Trying to reconnect...
[08:03:59] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: Remote host terminated the handshake
[08:03:59] [Paper Watchdog Thread/ERROR]: 	PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[08:03:59] [Paper Watchdog Thread/ERROR]: 	Stack:
[08:03:59] [pool-32-thread-1/WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: -1: javax.net.ssl.SSLHandshakeException
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:144)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:03:59] [pool-32-thread-1/WARN]: Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1513)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:93)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:201)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:141)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:124)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[08:03:59] [pool-32-thread-1/WARN]: 	... 3 more
[08:03:59] [pool-32-thread-1/WARN]: 	Suppressed: java.net.SocketException: Broken pipe
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:407)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[08:03:59] [pool-32-thread-1/WARN]: 		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:467)
[08:03:59] [pool-32-thread-1/WARN]: 		... 30 more
[08:03:59] [pool-32-thread-1/WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
[08:03:59] [pool-32-thread-1/WARN]: 	... 32 more
[08:03:59] [pool-32-thread-1/WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:144)
[08:03:59] [pool-32-thread-1/WARN]: 	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[08:03:59] [pool-32-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[08:03:59] [pool-32-thread-1/WARN]: 	... 3 more
[08:03:59] [Server thread/INFO]: com.mojang.authlib.GameProfile@3428d69b[id=0cb1e209-1e40-35a7-97a9-fe31b83a16a6,name=shinicore,properties={textures=[com.mojang.authlib.properties.Property@57b3c3aa]},legacy=false] (/218.102.120.73:58238) lost connection: Disconnected
[08:03:59] [Netty Epoll Server IO #1/ERROR]: Could not pass event StandardPaperServerListPingEventImpl to grakkit v6.0.1
java.lang.IllegalStateException: Multi threaded access requested by thread Thread[Netty Epoll Server IO #1,5,main] but is not allowed for language(s) js.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:1034) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:893) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:723) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:1991) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:110) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102) ~[grakkit-paper.jar:?]
	at com.oracle.truffle.polyglot.PolyglotFunctionProxyHandler.invoke(PolyglotFunctionProxyHandler.java:154) ~[grakkit-paper.jar:?]
	at jdk.proxy2.$Proxy122.execute(Unknown Source) ~[app:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
	at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:78) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.network.ServerStatusPacketListenerImpl.handleStatusRequest(ServerStatusPacketListenerImpl.java:149) ~[app:?]
	at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.handle(ServerboundStatusRequestPacket.java:19) ~[app:?]
	at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.handle(ServerboundStatusRequestPacket.java:6) ~[app:?]
	at net.minecraft.network.Connection.genericsFtw(Connection.java:303) ~[app:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:289) ~[app:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:54) ~[app:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) ~[ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:122) ~[app:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/sun.nio.fs.UnixNativeDispatcher.lstat0(Native Method)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/sun.nio.fs.UnixNativeDispatcher.lstat(UnixNativeDispatcher.java:308)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:72)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:434)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/java.nio.file.Files.move(Files.java:1432)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.Util$2.getAsBoolean(Util.java:462)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.Util.executeInSequence(Util.java:527)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.Util.runWithRetries(Util.java:538)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.Util.safeReplaceFile(Util.java:557)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.Util.safeReplaceFile(Util.java:550)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.world.level.storage.PlayerDataStorage.save(PlayerDataStorage.java:44)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.players.PlayerList.save(PlayerList.java:576)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:634)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:593)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2049)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2029)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.network.Connection.handleDisconnection(Connection.java:743)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1681)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer$$Lambda$3687/0x0000000801416880.run(Unknown Source)
[08:04:00] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
[08:04:00] [Paper Watchdog Thread/ERROR]: ------------------------------
[08:04:00] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[08:04:00] [Paper Watchdog Thread/ERROR]: ------------------------------
```

code:
```
core.command({
    name: 'test',
    execute: async (sender, rawargs) => {
        if(sender.getName() == "CONSOLE") return sender.sendMessage("no");

    }
})
core.command({
    name: 'asdf'
})
core.event("org.bukkit.event.server.ServerListPingEvent", (ev) => {
    ev.setMotd("test!");
    ev.setMaxPlayers(69)
})
```

**Comment by Mantou1233** [comment]
the error came when i added the `core.event` line

**Comment by Wolfo-Gaming** [comment]
Seems to be an issue with our graaljs implementation (?) as seen in this line:
```java.lang.IllegalStateException: Multi threaded access requested by thread Thread[Netty Epoll Server IO #1,5,main] but is not allowed for language(s) js.```
